### ISSUE TITLE
So, what's up with 0.2

### ISSUE THREAD

**Issue by messer00** [boraarslan/ark-guild-bot#5]
Do you need help? Are you able to progress the issue of lobbies de-scheduling?

**Comment by boraarslan** [comment]
Yes but the current problem is the codebase itself. Its basically a big mess. I can push 0.2 update in a couple days with the new content included but I have plans to rewrite certain parts (I mean most of the code). If you have any recommendations please open an issue so I can update the bot accordingly.

**Comment by messer00** [comment]
Sounds good. I should have more time to spend on these things next week, I'll help you out.
